### ISSUE TITLE
YError: Too many arguments provided.Expected max 2 but received 3. at argsert 

### ISSUE THREAD

**Issue by wkra** [rtCamp/VueTheme#34]
"YError: Too many arguments provided.Expected max 2 but received 3. at argsert " on "npm run dev" init.

Any solutions?

**Comment by sagarkbhatt** [comment]
@wkra 
Can you provide full stack trace ?

**Comment by dotKev** [comment]
```shellsession
$ npm install
up to date in 5.914s
$ npm run dev
> rt-vue-theme@1.0.0 dev /htdocs/gllt/wp-content/themes/gllt2018
> cross-env NODE_ENV=development webpack-dev-server --open --hot

YError: Too many arguments provided. Expected max 2 but received 3.
    at argsert (/htdocs/gllt/wp-content/themes/gllt2018/node_modules/webpack-dev-server/node_modules/yargs/lib/argsert.js:31:13)
    at Object.Yargs.self.alias (/htdocs/gllt/wp-content/themes/gllt2018/node_modules/webpack-dev-server/node_modules/yargs/yargs.js:237:5)
    at module.exports (/htdocs/gllt/wp-content/themes/gllt2018/node_modules/webpack/bin/config-yargs.js:12:4)
    at Object.<anonymous> (/htdocs/gllt/wp-content/themes/gllt2018/node_modules/webpack-dev-server/bin/webpack-dev-server.js:54:36)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
Project is running at http://localhost:8080/
webpack output is served from /dist/
404s will fallback to /index.html
```
